# Generated by Django 5.1.5 on 2025-01-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EN_ROUTE', 'En-route'), ('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RIDER', 'Rider'), ('DRIVER', 'Driver')], max_length=10),
        ),
    ]
