# Generated by Django 5.1.5 on 2025-01-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_management_app', '0002_alter_ride_status_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_time'], name='ride_manage_pickup__2671db_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='ride_manage_pickup__2ce3f8_idx'),
        ),
    ]
